# Generated by Django 5.0.2 on 2024-02-17 15:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='chibi_khras', max_length=40)),
                ('border', models.CharField(default='border01', max_length=40)),
                ('arena', models.CharField(default='arena01', max_length=40)),
                ('nickname', models.CharField(blank=True, default='', max_length=25)),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crystals', models.PositiveBigIntegerField(default=0)),
                ('patent_points', models.PositiveBigIntegerField(default=0)),
                ('patent', models.CharField(default='', max_length=15)),
                ('matches', models.PositiveBigIntegerField(default=0)),
                ('victories', models.PositiveBigIntegerField(default=0)),
                ('defeats', models.PositiveBigIntegerField(default=0)),
                ('friends', models.ManyToManyField(blank=True, to='dumcrown_api.player_data')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dumcrown_api_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
