# Generated by Django 5.0.2 on 2024-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown_api', '0002_player_data_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_data',
            name='patent',
            field=models.CharField(default='bronze', max_length=15),
        ),
    ]
