units_data = {
    1: {
        "id": 1,
        "type": "unit",
        "image": "jhon_card",
        "name": "JHON COPPER",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    2: {
        "id": 2,
        "type": "unit",
        "image": "carol_card",
        "name": "CAROL ARLET",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    3: {
        "id": 3,
        "type": "unit",
        "image": "mortem_card",
        "name": "MORTEM",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    4: {
        "id": 4,
        "type": "unit",
        "image": "kronos_card",
        "name": "KRONOS",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    5: {
        "id": 5,
        "type": "unit",
        "image": "darkage1_card",
        "name": "DARK AGE",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    6: {
        "id": 6,
        "type": "unit",
        "image": "khras_card",
        "name": "KHRAS",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    7: {
        "id": 7,
        "type": "unit",
        "image": "skillet_card",
        "name": "SKILLET",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    8: {
        "id": 8,
        "type": "unit",
        "image": "cdc_card",
        "name": "CDC",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    9: {
        "id": 9,
        "type": "unit",
        "image": "okada_card",
        "name": "OKADA",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    10: {
        "id": 10,
        "type": "unit",
        "image": "smoothcriminal_card",
        "name": "SMOOTH CRIMINAL",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    11: {
        "id": 11,
        "type": "unit",
        "image": "boogie_card",
        "name": "BOOGIE",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    12: {
        "id": 12,
        "type": "unit",
        "image": "spring_card",
        "name": "SPRING",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    13: {
        "id": 13,
        "type": "unit",
        "image": "polaroid_card",
        "name": "POLAROID",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    14: {
        "id": 14,
        "type": "unit",
        "image": "maniac_card",
        "name": "MANIAC",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    15: {
        "id": 15,
        "type": "unit",
        "image": "crazy_card",
        "name": "CRAZY",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    16: {
        "id": 16,
        "type": "unit",
        "image": "theojays_card",
        "name": "THE O'JAYS",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    17: {
        "id": 17,
        "type": "unit",
        "image": "neonb_card",
        "name": "NEON B.",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    18: {
        "id": 18,
        "type": "unit",
        "image": "ballhan_card",
        "name": "BALLHAN",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    19: {
        "id": 19,
        "type": "unit",
        "image": "darknecessites_card",
        "name": "DARK NECESSITES",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    20: {
        "id": 20,
        "type": "unit",
        "image": "anomaly_card",
        "name": "ANOMALY",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    },
    21: {
        "id": 21,
        "type": "unit",
        "image": "rhioros_ghost_card",
        "name": "RHIOROS GHOST",
        "description": "",
        "energy": 4,
        "attack": 8,
        "defense": 6,
    }
}
