services:
  dum_django:
    container_name: dum_django
    image: dumcrown:latest
    build:
      context: .
    ports:
      - 80:8000
    volumes:
      - ./dumcrown:/dumcrown
      - ./dumcrown/dumcrown/static/dumcrown:/dumcrown/static/dumcrown
      - ./dumcrown/media:/dumcrown/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - dum_psql
      - dum_redis

  dum_redis:
    container_name: dum_redis
    restart: unless-stopped
    image: redis:8.0
    ports:
      - 6379:6379
    command: [ "redis-server", "--save", "" ]

  dum_psql:
    container_name: dum_psql
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

volumes:
  database:
