version: '3.3'

services:
  dumcrown:
    container_name: dumcrown
    build:
      context: .
    ports:
      - 8000:8000 
    volumes:
      - ./dumcrown:/dumcrown
      - ./dumcrown/static:/dumcrown/static/
      - ./dumcrown/media:/dumcrown/media/
      - ./ssl:/ssl  
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - redis
      - celery 

  redis:
    restart: always
    image: redis:6.2
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  psql:
    container_name: psql
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  celery:  
    build:
      context: .
    command: celery -A project worker -l info
    volumes:
      - ./dumcrown:/dumcrown
      - ./dumcrown/dumcrown/static:/dumcrown/static/
      - ./dumcrown/media:/dumcrown/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - redis

  nginx:  
    container_name: nginx
    image: nginx:1.25.1
    ports:
      - 80:80 
      - 443:443  
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./ssl:/ssl  
      - ./certbot:/usr/share/nginx/html/.well-known/acme-challenge 
      - ./dumcrown/static:/dumcrown/static/
    depends_on:
      - dumcrown

volumes:
  redisdata:
  dumcrown-static:
