services:
  dumcrown:
    container_name: dumcrown
    build:
      context: .
    ports:
      - 8001:8001
    volumes:
      - ./dumcrown:/dumcrown
      - ./dumcrown/dumcrown/static/dumcrown:/dumcrown/static/1.0.0/dumcrown
      - ./dumcrown/media:/dumcrown/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql_dum
      - redis

  redis:
    restart: always
    image: redis:6.2
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    command: [ "redis-server", "--save", "" ]

  psql_dum:
    container_name: psql_dum
    image: postgres:13-alpine
    ports:
      - 5433:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

volumes:
  redisdata:
