services:
  dum_django:
    container_name: dum_django
    image: dumcrown:latest
    build:
      context: .
    ports:
      - 80:8000
    volumes:
      - ./dumcrown:/dumcrown
      - ./dumcrown/dumcrown/static/dumcrown:/dumcrown/static/dumcrown
      - ./dumcrown/media:/dumcrown/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      dum_psql:
        condition: service_healthy
      dum_redis:
        condition: service_started
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             daphne -b 0.0.0.0 -p 8000 core.asgi:application"

  dum_redis:
    container_name: dum_redis
    restart: unless-stopped
    image: redis:8.0
    ports:
      - 6379:6379
    command: [ "redis-server", "--save", "" ]

  dum_psql:
    container_name: dum_psql
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database:
