version: '3.9'

services:
  dumcrown:
    container_name: dumcrown
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./dumcrown:/dumcrown
      - ./dumcrown/static:/dumcrown/static/
      - ./dumcrown/media:/dumcrown/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
