# Generated by Django 4.2.16 on 2024-09-21 14:23

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=25)),
                ('icon', models.CharField(default='chibi_khras', max_length=40)),
                ('border', models.CharField(default='border01', max_length=40)),
                ('arena', models.CharField(default='arena01', max_length=40)),
                ('level', models.PositiveIntegerField(default=1)),
                ('cards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=['1', '2', '3', '5', '8', '9', '11', '12', '13', '15', '18', '21', 's1', 's8', 's2', 's5', 's7'], size=None)),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('crystals', models.PositiveBigIntegerField(default=0)),
                ('tier', models.CharField(default='bronze', max_length=15)),
                ('crown_points', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('current_deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_deck_for_players', to='dumcrown.deck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveBigIntegerField(default=0)),
                ('victories', models.PositiveBigIntegerField(default=0)),
                ('defeats', models.PositiveBigIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='dumcrown.player')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_music', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('soundsfx_volume', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='dumcrown.player')),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='dumcrown.player')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='dumcrown.player'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, default='', max_length=1000)),
                ('is_online', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='dumcrown.player')),
            ],
        ),
    ]
