# Generated by Django 5.0.4 on 2024-04-13 16:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=25)),
                ('icon', models.CharField(default='chibi_khras', max_length=40)),
                ('border', models.CharField(default='border01', max_length=40)),
                ('arena', models.CharField(default='arena01', max_length=40)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('crystals', models.PositiveBigIntegerField(default=0)),
                ('tier', models.CharField(default='bronze', max_length=15)),
                ('crown_points', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='dumcrown.player')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, default='', max_length=1000)),
                ('is_online', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='dumcrown.player')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_music', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('soundsfx_volume', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='dumcrown.player')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveBigIntegerField(default=0)),
                ('victories', models.PositiveBigIntegerField(default=0)),
                ('defeats', models.PositiveBigIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='dumcrown.player')),
            ],
        ),
    ]
