# Generated by Django 5.0.1 on 2024-01-27 15:25

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('chibi_khras', 'khras'), ('chibi_kronos', 'kronos'), ('chibi_lda', 'lda')], default='chibi_khras', max_length=40)),
                ('border', models.CharField(choices=[('border01', 'borda 1'), ('border02', 'borda 2'), ('border03', 'borda 3')], default='border01', max_length=40)),
                ('arena', models.CharField(choices=[('arena01', 'arena 1'), ('arena02', 'arena 2')], default='arena01', max_length=40)),
                ('nickname', models.CharField(blank=True, default='', max_length=25)),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crystals', models.PositiveBigIntegerField(default=0)),
                ('crown_points', models.PositiveBigIntegerField(default=0)),
                ('friends_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, default=list, size=None)),
                ('volume_music', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('soundsfx_volume', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('matches', models.PositiveBigIntegerField(default=0)),
                ('victories', models.PositiveBigIntegerField(default=0)),
                ('defeats', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_match_id', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Match_loser', to='dumcrown.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Match_winner', to='dumcrown.player')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
