# Generated by Django 4.2.16 on 2024-09-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_deck', to='dumcrown.deck'),
        ),
    ]
