# Generated by Django 5.0.1 on 2024-02-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tier',
            field=models.CharField(default='bronze', max_length=15),
        ),
    ]
