# Generated by Django 5.0.4 on 2024-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active_deck_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
