# Generated by Django 5.0.4 on 2024-05-30 19:01

import django.contrib.postgres.fields
import django.db.models.deletion
import dumcrown.models.default_values
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0002_player_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=dumcrown.models.default_values.initial_cards, size=None),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='dumcrown.player')),
            ],
        ),
    ]
