# Generated by Django 4.2.16 on 2024-10-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0002_alter_player_current_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='arena',
        ),
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.CharField(default='arena01', max_length=40),
        ),
    ]
