# Generated by Django 5.0.4 on 2024-07-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0002_player_active_deck_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='active_deck_id',
        ),
    ]
