# Generated by Django 4.2.16 on 2024-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0003_remove_player_arena_player_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='board',
            field=models.CharField(default='default_board', max_length=40),
        ),
    ]
