# Generated by Django 5.0.4 on 2024-05-30 19:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0003_alter_player_cards_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=['1', '2', '3', '5', '8', '9', '11', '12', '13', '15', '18', '21', 's1', 's8', 's2', 's5', 's7'], size=None),
        ),
    ]
