# Generated by Django 4.2.17 on 2025-04-21 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumcrown', '0005_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=['1', '2', '3', '5', '8', '9', '11', '12', '13', '15', '18', '21', 's1', 's2', 's7', 's8'], size=None),
        ),
    ]
